# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'E-BookStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-BookStore

  target 'E-BookStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-BookStoreUITests' do
    # Pods for testing
    pod 'Firebase/Firestore'
   # Optionally, include the Swift extensions if you're using Swift.
    pod 'FirebaseFirestoreSwift'

  end

end
